# Generated by Django 5.2.6 on 2025-09-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Vehicle manufacturer, e.g., Toyota, Ford.', max_length=50, verbose_name='Make')),
                ('model', models.CharField(help_text='Vehicle model, e.g., Corolla, Mustang.', max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year, e.g., 2020.', verbose_name='Year')),
                ('license_plate', models.CharField(help_text='Unique license plate number.', max_length=20, unique=True, verbose_name='License Plate')),
                ('vin', models.CharField(help_text='Vehicle Identification Number.', max_length=17, unique=True, verbose_name='VIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
