# Generated by Django 5.2.6 on 2025-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Oil Change, Engine Repair', max_length=100, unique=True, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, help_text='Details about the service', null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the service in USD', max_digits=10, verbose_name='Price')),
                ('duration', models.DurationField(help_text='Estimated time to complete the service, e.g., 01:30:00 for 1.5 hours', verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
    ]
