# Generated by Django 5.2.6 on 2025-09-22 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for the report', verbose_name='Month')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Revenue')),
                ('total_bookings', models.IntegerField(verbose_name='Total Bookings')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Average Customer Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revenue Report',
                'verbose_name_plural': 'Revenue Reports',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Month')),
                ('completed_bookings', models.IntegerField(verbose_name='Completed Bookings')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Revenue Generated')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Average Feedback Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performances',
                'ordering': ['-month', 'staff'],
            },
        ),
    ]
